// SPEC §Copywriting Contract — every user-visible string lives here.
// Ported verbatim from prototype src/lib/copy.js (2026-05-06). Typed `as const`.

export const COPY = {
  'dev.bodySway.title': 'Body-sway strategy',
  'dev.bodySway.headOnly': 'head_only',
  'dev.bodySway.proxyParam': 'proxy_param (Lean Forward)',
  'dev.bodySway.exp3Modulation': 'exp3_modulation (.exp3.json)',
  APP: {
    TITLE: 'AgenticLLMVTuber'
  },
  SETUP: {
    HEADER: 'Connect a language model',
    SUB: 'AgenticLLMVTuber sends every message to a language model you control.',
    PROVIDER_LABEL: 'Provider',
    ENDPOINT_LABEL: 'Endpoint URL',
    ENDPOINT_HELP: '(http://… or https://…)',
    MODEL_LABEL: 'Model',
    MODEL_HELP: 'auto-detect if blank',
    APIKEY_LABEL: 'API key',
    APIKEY_PLACEHOLDER: 'LM Studio: skip',
    TEST_BTN: 'Test connection',
    TEST_BTN_RUNNING: 'Testing…',
    LOG_TITLE: 'Connection test log',
    HELP_LINK: 'Setup help ↗',
    CONTINUE: 'Continue →',
    ERROR_UNREACHABLE_TITLE: 'LLM unreachable',
    ERROR_UNREACHABLE_STEPS: [
      'LM Studio is open.',
      'A model is loaded in the chat tab.',
      'Local server is running on the endpoint above.'
    ]
  },
  LLM_SETUP: {
    HEADER: 'Connect a language model',
    SUB: 'AgenticLLMVTuber sends every message to a language model you control.',
    PROVIDER_LABEL: 'Provider',
    ENDPOINT_LABEL: 'Endpoint URL',
    ENDPOINT_PLACEHOLDER: 'http://localhost:1234/v1',
    MODEL_LABEL: 'Model',
    MODEL_HELPER: 'auto-detect if blank',
    MODEL_PLACEHOLDER: 'auto-detect',
    APIKEY_LABEL: 'API key',
    APIKEY_HELPER_LMSTUDIO: 'LM Studio: skip',
    CTA_TEST: 'Test connection',
    CTA_TEST_AGAIN: 'Test connection again',
    CTA_CONTINUE: 'Continue →',
    SUCCESS_FINAL: 'Connection looks good. You can continue.',
    DISABLED_PROVIDER_TT:
      'Hosted-provider support lands in v2. Use the Custom OpenAI-compatible option for now if you need a hosted endpoint.',
    PROVIDERS: [
      { id: 'lmstudio', label: 'LM Studio', status: '✓ working', enabled: true },
      { id: 'custom', label: 'Custom OpenAI-compat', status: '✓ working', enabled: true },
      { id: 'openai', label: 'OpenAI', status: '⏳ Coming v2', enabled: false },
      { id: 'anthropic', label: 'Anthropic', status: '⏳ Coming v2', enabled: false },
      { id: 'gemini', label: 'Gemini', status: '⏳ Coming v2', enabled: false }
    ]
  },
  CHAT: {
    EMPTY_VTS_HEAD: 'To see your avatar, start VTube Studio and load a Live2D model.',
    EMPTY_VTS_BODY: "We'll connect automatically.",
    EMPTY_VTS_LINK: 'Open VTube Studio docs ↗',
    EMPTY_READY_HEAD: 'Your avatar is ready.',
    EMPTY_READY_BODY: 'Type below to start a conversation.',
    EMPTY_READY_FOOTER: 'Completed turns are saved locally in conversation history.',
    INPUT_PLACEHOLDER: 'Type a message...',
    // Phase 2 (plan 02-03) -- streaming-chat affordances. Single-char ellipsis
    // (U+2026) per UI-SPEC §Typography (italic --muted-foreground).
    THINKING: 'Thinking…',
    SPEAKING: 'Teto is still speaking…',
    STREAM_ERROR: "The model couldn't finish that reply. Try again.",
    GPT_SOVITS_AUDIO_FAILED_SENTENCE: 'Audio failed for this sentence. Text is still shown.',
    GPT_SOVITS_NEXT_TURN_FALLBACK: 'GPT-SoVITS failed. Select Piper for the next turn if you want fallback audio.',
    GPT_SOVITS_OPEN_LOGS: 'Open logs for details.',
    CONTEXT_OVERFLOW:
      "Conversation got too long and won't fit in the model anymore. Start a new chat to continue."
  },
  HISTORY: {
    HEADER: 'History',
    NEW_THREAD: 'New chat',
    SEARCH: 'Search sessions',
    SEARCH_LABEL: 'Search conversation sessions',
    LOADING: 'Loading local history...',
    ERROR: 'Could not load local history.',
    EMPTY_HEAD: 'No matching sessions.',
    EMPTY_BODY: 'Create a new chat or change the search.',
    EMPTY_PREVIEW: 'No messages yet',
    GROUP_TODAY: 'Today',
    GROUP_YESTERDAY: 'Yesterday',
    GROUP_PREVIOUS_7: 'Previous 7 days',
    GROUP_OLDER: 'Older',
    RENAME: 'Rename',
    RENAME_INPUT_LABEL: 'Session title',
    RENAME_SAVE: 'Save',
    RENAME_CANCEL: 'Cancel',
    DELETE: 'Delete',
    DELETE_CONFIRM: 'Delete this conversation session?'
  },
  AGENT: {
    PLACEHOLDER_HEAD: 'Agent mode arrives in milestone-3.',
    PLACEHOLDER_BODY:
      "You'll be able to delegate goals to a computer-use sub-agent (daily routines, GUI workflows) and a CLI sub-agent (code/file/web tasks via Claude Code).",
    TOGGLE_DISABLED_TT: 'Agent mode arrives in milestone-3.'
  },
  STATUS: {
    HEADER: 'Status',
    LLM: 'LLM',
    VTS: 'VTS',
    SIDECAR: 'Sidecar',
    PLUGIN: 'Plugin',
    PLUGIN_DETAILS: 'Plugin details',
    RETEST: 'Re-test connection',
    TESTING: 'Testing...',
    REFRESH: 'Refresh status',
    REFRESHING: 'Refreshing...'
  },
  SETTINGS: {
    HEADER: 'Settings',
    ANCHORS_HINT: 'Connection · Avatars · VTube Studio · …',
    CONN_HEADER: 'Connection / Models',
    CONN_RETEST: 'Re-test',
    CONN_REFRESH: 'Refresh status',
    CONN_CHANGE: 'Edit connection',
    CONN_SAVE: 'Save connection',
    CONN_SAVING: 'Saving...',
    CONN_CANCEL: 'Cancel',
    CONN_TEST: 'Test connection',
    CONN_TEST_AGAIN: 'Test connection again',
    CONN_SAVED: 'Saved. Status refreshed.',
    CONN_ERROR: 'Could not save connection settings.',
    AVATARS_HEADER: 'Avatars',
    AVATARS_HELP: 'Active avatar identity and catalog state from the sidecar.',
    AVATARS_ID: 'Avatar ID',
    AVATARS_NAME: 'Name',
    AVATARS_SOURCE: 'Source path',
    AVATARS_VARIANTS: 'Variants',
    AVATARS_EVENTS: 'Events',
    AVATARS_VOICE: 'Voice',
    AVATARS_NO_VOICE: 'No voice configured',
    AVATARS_LOADING: 'Loading current avatar catalog...',
    AVATARS_UNKNOWN_ID: 'Unavailable',
    AVATARS_DEGRADED: 'Avatar ID is known, but the saved editable catalog has not loaded yet. Wait for the sidecar status to finish loading, then try Edit current again. If this avatar was never imported, use Import/replace.',
    AVATARS_DEGRADED_UNKNOWN: 'Current avatar ID and saved editable catalog are unavailable. Wait for the sidecar status to finish loading, then use Import/replace if needed.',
    AVATARS_EDIT_CURRENT: 'Edit current',
    AVATARS_IMPORT_REPLACE: 'Import/replace',
    AVATARS_EDIT_UNAVAILABLE: 'Current avatar catalog is not available to edit.',
    PLUGINS_HEADER: 'Body motion plugin',
    PLUGINS_HELP: 'Changing the selection saves your config and restarts the sidecar automatically.',
    PLUGINS_EMPTY: 'No body motion plugins found.',
    PLUGINS_SAVING: 'Saving...',
    PLUGINS_SAVED: 'Saved. Sidecar restarted.',
    PLUGINS_ERROR: 'Could not save plugin selection.',
    PLUGINS_CURSOR_TRACKING: 'Cursor tracking',
    PLUGINS_CURSOR_TRACKING_HELP: 'Use cursor position for head and eye tracking. Changing this restarts the sidecar.',
    VTS_HEADER: 'VTube Studio',
    VTS_HELP: 'Compact status mirror. Use the upper-right Status menu for the primary live status view.',
    VTS_STATUS: 'Status',
    VTS_WINDOW: 'VTS window',
    VTS_AUTH: 'Authorization',
    VTS_WINDOW_DETECTED: 'Detected',
    VTS_WINDOW_MISSING: 'Not detected',
    VTS_AUTHENTICATED: 'Authorized',
    VTS_NOT_AUTHENTICATED: 'Not authorized',
    VTS_TROUBLESHOOTING: 'Troubleshooting',
    VTS_RESTART: 'Restart sidecar',
    VTS_RESET_AUTH: 'Reset/re-auth VTS token',
    VTS_RESET_HELP: 'Deletes the stored VTS plugin token and restarts the sidecar so VTube Studio can ask for authorization again.',
    VTS_ACTION_DONE: 'Action complete. Status refreshed.',
    VTS_ACTION_ERROR: 'Troubleshooting action failed.',
    APPEARANCE_HEADER: 'Appearance',
    MODE_LABEL: 'Mode',
    MODE_OPTIONS: [
      { id: 'auto', label: 'Match system', isDefault: true },
      { id: 'light', label: 'Light' },
      { id: 'dark', label: 'Dark' }
    ],
    LIGHT_ACCENT_LABEL: 'Light accent',
    LIGHT_ACCENT_HELP: 'Used when the app is in light mode.',
    LIGHT_ACCENT_OPTIONS: [
      { id: 'blush', label: 'Blush', isDefault: true },
      { id: 'sunrise', label: 'Sunrise' },
      { id: 'ember', label: 'Ember' }
    ],
    DARK_BG_LABEL: 'Dark background',
    DARK_BG_HELP: 'Used when the app is in dark mode.',
    DARK_BG_OPTIONS: [
      { id: 'midnight', label: 'Midnight', isDefault: true },
      { id: 'onyx', label: 'Onyx' }
    ],
    DARK_ACCENT_LABEL: 'Dark accent',
    DARK_ACCENT_HELP: 'Used when the app is in dark mode.',
    DARK_ACCENT_OPTIONS: [
      { id: 'sky', label: 'Sky', isDefault: true },
      { id: 'pewter', label: 'Pewter' }
    ],
    PREVIEW_HEADER: 'Preview',
    DISABLED_LIGHT_TT: 'Active when Light mode resolves.',
    DISABLED_DARK_TT: 'Active when Dark mode resolves.',
    DIAG_HEADER: 'Diagnostics',
    DIAG_SHOW_LOGS: 'Show log panel',
    DIAG_SHOW_LOGS_HINT: 'Sidecar logs appear in a drawer above the bottom rail.',
    DIAG_OPEN_FOLDER: 'Open log folder',
    DIAG_RESET: 'Reset all state',
    DIAG_LOG_LEVEL: 'Log level',
    DIAG_LOG_LEVEL_HELP: 'Filters renderer/main-process UI logging preference.',
    DIAG_LOG_LEVEL_DESCRIPTIONS_LABEL: 'Log level meanings',
    DIAG_LOG_LEVEL_DESCRIPTIONS: [
      { id: 'error', label: 'Error', description: 'only failures that need intervention.' },
      { id: 'warn', label: 'Warn', description: 'problems that need attention, plus errors.' },
      { id: 'info', label: 'Info', description: 'normal app milestones, warnings, and errors.' },
      { id: 'debug', label: 'Debug', description: 'verbose troubleshooting detail, plus all other logs.' }
    ],
    DIAG_TELEMETRY: 'Telemetry',
    DIAG_TELEMETRY_HELP: 'Coming in milestone-5. Telemetry is opt-in only.',
    TTS_HEADER: 'TTS / Voice out',
    TTS_ENGINE: 'Engine',
    TTS_ENGINE_VAL: 'Piper local TTS',
    TTS_VOICE: 'Voice',
    TTS_VOICE_VAL: 'en_US-amy-medium',
    TTS_OUTPUT: 'Output device',
    TTS_OUTPUT_VAL: 'System default',
    TTS_LIPSYNC: 'Lipsync',
    TTS_LIPSYNC_VAL: 'VTube Studio ParamMouthOpenY from RMS volume',
    TTS_HELP: 'Phase 3 is active: replies synthesize locally and play through the default audio device. Broader STT/TTS settings continue in v3.0.',
    TTS_PROVIDER_GROUP: 'TTS provider',
    TTS_PROVIDER_PIPER: 'Piper local TTS',
    TTS_PROVIDER_GPT_SOVITS: 'GPT-SoVITS',
    TTS_PROVIDER_PIPER_HELP: 'Local baseline. Selecting Piper saves immediately.',
    TTS_PROVIDER_GPT_HELP: 'Requires health check and audible test synthesis before activation.',
    GPT_SOVITS_SETUP_HEADER: 'GPT-SoVITS setup',
    GPT_SOVITS_BASE_URL: 'Base URL',
    GPT_SOVITS_CONNECTION_MODE: 'Connection mode',
    GPT_SOVITS_EXTERNAL_MODE: 'External server',
    GPT_SOVITS_APP_MANAGED_MODE: 'App-launched command',
    GPT_SOVITS_COMMAND: 'Command',
    GPT_SOVITS_WORKING_DIRECTORY: 'Working directory',
    GPT_SOVITS_HEALTH_URL: 'Health URL',
    GPT_SOVITS_HEALTH_CHECK: 'Run health check',
    GPT_SOVITS_TEST_SYNTHESIS: 'Test synthesis',
    GPT_SOVITS_ACTIVATE_PRESET: 'Activate voice preset',
    GPT_SOVITS_PROVIDER_NOT_READY: 'Run health check and test synthesis before activating GPT-SoVITS.',
    GPT_SOVITS_HEALTH_PASSED_TEST_PENDING: 'Server is reachable. Test synthesis is still required.',
    GPT_SOVITS_ACTIVATION_SUCCESS: 'GPT-SoVITS activation saved and the sidecar restarted. Chat will use GPT-SoVITS on the next turn.',
    GPT_SOVITS_ACTIVATION_RUNTIME_MISMATCH: 'Activation saved, but the runtime still reports Piper. Open logs for details before chatting.',
    GPT_SOVITS_CANDIDATE_FAILURE: 'Test failed. Keeping the previous provider and preset.',
    GPT_SOVITS_TEST_FAILED_DETAIL: 'GPT-SoVITS test failed. Your current voice settings were not changed. Open logs for details, then check the server and reference audio.',
    GPT_SOVITS_REFERENCE_PATH_FAILURE: 'GPT-SoVITS could not read the copied reference audio. Open logs for details.',
    GPT_SOVITS_PREVIEW_READY: 'Test synthesis preview played.',
    VOICE_PRESETS_HEADER: 'Voice presets',
    VOICE_PRESETS_EMPTY_HEAD: 'No voice presets yet.',
    VOICE_PRESETS_EMPTY_BODY: 'Enter preset details, import reference audio, then click New preset to save it.',
    VOICE_PRESET_NAME: 'Voice preset name',
    VOICE_PRESET_NEW: 'New preset',
    VOICE_PRESET_SAVE: 'Save preset',
    VOICE_PRESET_SAVE_SUCCESS: 'Voice preset saved.',
    VOICE_PRESET_CREATE_SUCCESS: 'New voice preset saved.',
    VOICE_PRESET_SAVE_FAILURE: 'Voice preset could not be saved. Open logs for details.',
    VOICE_PRESET_SAVE_MISSING_REFERENCE: 'Preset was not saved. Add reference transcript, choose a language, and import or select reference audio first.',
    VOICE_PRESET_SAVE_BLOCKED_TITLE: 'Preset was not saved',
    VOICE_PRESET_SAVE_BLOCKED_CLOSE: 'Review missing fields',
    VOICE_PRESET_SAVE_NO_SELECTION: 'Select an existing preset to update, or click New preset to save the current fields as a separate preset.',
    VOICE_PRESET_DELETE: 'Delete voice preset',
    VOICE_PRESET_DELETE_CONFIRM: 'Delete preset',
    VOICE_PRESET_DELETE_BLOCKED: 'Delete voice preset? Choose another active preset before deleting this one.',
    VOICE_PRESET_DELETE_CANCEL: 'Cancel',
    VOICE_PRESET_ACTIVE_NOTE: 'Fill the fields first. New preset saves the current fields as a separate preset; Save preset updates the selected preset.',
    REFERENCE_AUDIO_HEADER: 'Reference audio',
    REFERENCE_AUDIO_IMPORT: 'Import reference audio',
    REFERENCE_AUDIO_REQUIRED: 'Reference transcript and language are required before import.',
    REFERENCE_AUDIO_READY: 'Reference transcript and language are ready. Import an audio file to attach it.',
    REFERENCE_AUDIO_IMPORT_SUCCESS: 'Reference audio imported and selected.',
    REFERENCE_AUDIO_IMPORT_FAILURE: 'Reference audio import failed. Open logs for details.',
    REFERENCE_AUDIO_TRANSCRIPT: 'Reference transcript',
    REFERENCE_AUDIO_LANGUAGE: 'Reference language',
    REFERENCE_AUDIO_DELETE: 'Delete reference audio',
    REFERENCE_AUDIO_DELETE_BLOCKED: (count: number) => `Reference audio is used by ${count} preset(s). Reassign those presets before deleting it.`,
    REFERENCE_AUDIO_DELETE_CANCEL: 'Cancel',
    REFERENCE_AUDIO_VALIDATION_FORMAT: 'Format',
    REFERENCE_AUDIO_VALIDATION_DURATION: 'Duration',
    REFERENCE_AUDIO_VALIDATION_METADATA: 'Metadata',
    REFERENCE_AUDIO_VALIDATION_SERVER_ACCESS: 'Server access',
    GPT_SOVITS_START: 'Start GPT-SoVITS',
    GPT_SOVITS_STOP_APP_LAUNCHED: 'Stop app-launched GPT-SoVITS',
    GPT_SOVITS_RESTART_APP_LAUNCHED: 'Restart app-launched GPT-SoVITS',
    GPT_SOVITS_STOP_CONFIRM: 'Stop app-launched GPT-SoVITS? This only stops the process AgenticLLMVTuber started.',
    GPT_SOVITS_EXTERNAL_STOP_HELP: 'External server — stop it outside AgenticLLMVTuber.',
    GPT_SOVITS_NON_LOCAL_WARNING: 'Advanced: this sends text/reference paths to a non-local GPT-SoVITS server.',
    CONVERSATION_HEADER: 'Conversation',
    CONVERSATION_MODE: 'History',
    CONVERSATION_MODE_VAL: 'Local transcript sessions',
    CONVERSATION_ACTIVE: 'Active session',
    CONVERSATION_SESSIONS: 'Sessions',
    CONVERSATION_MESSAGES: 'Messages',
    CONVERSATION_RESET: 'Retention',
    CONVERSATION_RESET_VAL: 'Saved locally until you delete a session or clear history.',
    CONVERSATION_HELP: 'History stores transcript sessions only. Memory, retrieval, and per-avatar facts remain v4.0 scope.',
    CONVERSATION_CLEAR: 'Clear all history',
    CONVERSATION_CLEAR_TITLE: 'Clear conversation history?',
    CONVERSATION_CLEAR_BODY: 'This deletes all saved conversation sessions and creates a fresh New chat. Provider settings and memory settings are not changed.',
    CONVERSATION_CLEAR_CONFIRM: 'Clear history',
    CONVERSATION_CLEAR_DONE: 'Conversation history cleared.',
    MEMORY_HEADER: 'Memory',
    MEMORY_STATUS: 'Status',
    MEMORY_STATUS_VAL: 'Disabled',
    MEMORY_HELP: 'Memory ships with v4.0 agentic system plus memory. No shared facts, retrieval index, or remember-this controls are active yet.',
    ABOUT_HEADER: 'About',
    ABOUT_VERSION: 'Version',
    ABOUT_VERSION_VAL: 'v2.1 Mock/Reality Cleanup',
    ABOUT_CHANNEL: 'Update channel',
    ABOUT_CHANNEL_VAL: 'Coming in milestone-5.',
    ABOUT_LINKS: 'Docs · License · Third-party notices',
    PLACEHOLDERS: [
      // §2-§13 from SPEC IA table
      { num: 6, title: 'Voice in', milestone: 3, body: 'Push-to-talk key, VAD sensitivity, ASR model size, interrupt behavior.' },
      { num: 9, title: 'Skills', milestone: 4, body: 'Install skills from a folder, grant per-skill permissions.' },
      { num: 10, title: 'Agent', milestone: 4, body: 'Default permissions, file-ops allowlist, audit log, kill-switch hotkey.' },
      { num: 11, title: 'Scheduler', milestone: 4, body: 'Saved goal templates, cron schedules, missed-runs behavior.' },
      { num: 12, title: 'Form factor', milestone: 4, body: 'Window vs pet mode, opacity, click-through, always-on-top, drag inertia.' },
      { num: 13, title: 'Hotkeys', milestone: 4, body: 'Customize the kill-switch, push-to-talk, hide-window, and test-prop bindings.' }
    ]
  },
  HUD: {
    HUD_HEADING: 'Slider HUD',
    OPEN_HUD_BUTTON: 'Open HUD',
    OPEN_HUD_HELP: 'Open the slider HUD to inspect and lock individual rig parameters.',
    FILTER_WRITABLE: 'Writable',
    FILTER_ANIMATING: 'Animating',
    FILTER_LOCKED: 'Locked',
    FOOTER_TEMPLATE: '{N} params · {M} locked · 15 Hz',
    EMPTY_FILTER_HEADING: 'No params match the active filters.',
    EMPTY_FILTER_BODY: 'Toggle a chip back on to see more params.',
    EMPTY_RIG_HEADING: 'This rig exposes no parameters the HUD can lock.',
    EMPTY_RIG_BODY: 'Add or import a rig with at least one writable parameter.',
    LOADING_BODY: 'Loading rig parameters…',
    LOADING_ERROR: "Couldn't load rig parameters. Is the sidecar running?",
    RETRY_BUTTON: 'Retry',
    BANNER_DISCONNECTED: 'HUD lost connection to the sidecar. Reconnecting…',
    TOAST_LOCKS_CLEARED: 'Avatar changed — locks cleared.'
  },
  ERRORS: {
    LLM_UNREACHABLE_BANNER: 'LLM is unreachable. Start LM Studio and click Retry.',
    VTS_DISCONNECTED: 'VTube Studio disconnected — avatar motion paused. Will reconnect when VTS is back.',
    VTS_AUTH_DENIED: 'Plugin authorization denied in VTube Studio. [Re-request] or grant in VTS → Settings → Plugins.',
    SIDECAR_RESTART: 'Sidecar restarting...',
    SIDECAR_REPEAT: 'Sidecar has crashed twice. Click Restart sidecar or check the log folder for details.',
    SIDECAR_TOAST: 'Sidecar crashed — restarting...',
    TTS_UNAVAILABLE: 'TTS unavailable — replies will be text-only. [More info]',
    REFUSED_LMSTUDIO_HEAD: "LM Studio doesn't seem to be running.",
    NO_MODEL: 'No model is loaded in LM Studio.'
  },
  RESET: {
    TITLE: 'Reset all state?',
    BODY: 'This clears your provider configuration, appearance preferences, window settings, and any other saved preferences. The next launch will start at the LLM setup screen. This cannot be undone.',
    CANCEL: 'Cancel',
    CONFIRM: 'Reset everything'
  },
  AVATAR_IMPORT: {
    PAGE_TITLE: 'Import Avatar',
    PAGE_SUBTITLE: 'Review the auto-detected variants + events from your rig and Save when ready.',
    IMPORT_BUTTON_LABEL: 'Choose folder…',
    SETTINGS_BUTTON_LABEL: 'Edit avatar catalogs',
    SAVE_BUTTON_LABEL: 'Save catalogs',
    SAVE_DISABLED_PLACEHOLDER: (n: number) =>
      `Save disabled — ${n} placeholder name${n === 1 ? '' : 's'} remain. Click here to scroll to the first.`,
    VARIANTS_HEADING: 'Variants (toggle expressions)',
    VARIANTS_EMPTY: 'This rig exposes no toggle expressions.',
    EVENTS_HEADING: 'Events (one-shot motions)',
    EVENTS_EMPTY: 'This rig exposes no motion events.',
    SOURCE_NAME_HEADING: 'Source name (rig-side)',
    CODE_HEADING: 'Code (LLM-facing)',
    PREVIEW_HEADING: 'Preview',
    DELETE_LABEL: 'Delete row',
    SUCCESS_TOAST: 'Avatar imported successfully',
    ERROR_CUBISM_5_3:
      "This avatar uses Cubism 5.3 features that VTube Studio doesn't support yet. " +
      'Please re-export the rig from Cubism Editor with target version 5.2 or earlier.',
    ERROR_NO_MODEL3:
      "This folder doesn't look like a runtime Live2D export. " +
      'If you have a .cmo3 Cubism Editor project, export it first ' +
      '(File → Export to .moc3 in Cubism Editor).',
    NEW_BADGE: 'NEW',
    EDITED_BADGE: 'edited',
    CANCEL_BUTTON_LABEL: 'Cancel',
    VALIDATION_ERROR_RESERVED: (code: string) => `'${code}' is a reserved LLM-protocol name`,
    VALIDATION_ERROR_DUPLICATE: (code: string) => `'${code}' is already used by another row`,
    VALIDATION_ERROR_SLUG: 'Code must match a-z 0-9 hyphens, start with a letter, max 31 chars',
    DETECTED_TYPE_LABEL: 'Detected type',
    SOURCE_PATH_LABEL: 'Source path',
    WARNINGS_HEADING: 'Import warnings',
    SAVE_ERROR_FALLBACK: 'Could not save avatar catalogs.'
  },
  LOGS: {
    COLLAPSED: 'Logs',
    CLEAR: 'Clear logs',
    OPEN_FOLDER: 'Open log folder',
    // Phase 7 -- structured dispatch log prefix; styled green in
    // the LogsDrawer per UI-SPEC IP-4. 8-char prefix matches [READY]/[ERROR]
    // width-class for visual scan symmetry.
    DISPATCH_PREFIX: '[DISPATCH]'
  }
} as const
